# Site settings
title: Metro PDX Soccer
description: "Portland 7v7 soccer league for men, women, and coed"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo:
    url: svg/min/logo.svg

# Hero
hero:
    hero_bg: bannerbg.jpg
    hero_img: banner.jpg
    hero_logo: logo.jpg
    hero_title: Metro PDX Soccer
    hero_description: A responsive Jekyll theme for dental clinics.

# Contact form
api_token: # Enter API token here

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 14
    address: 11999 Southeast Fuller Road, Milwaukie, OR 97222
    address_details: svg/min/logo.svg

# Social settings
social:
    # facebook: http://facebook.com
    # twitter: http://twitter.com
    # instagram: http://instagram.com
    # youtube: http://youtube.com
    # skype: skype:obaez_design?userinfo
    # feed: yes

# Footer
copyright: © 2016 MetroPDXSoccer - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics:
google_verification:
